messages:
  place-gen: "&a✔ Du placerede en generator!"
  remove-gen: "&c✘ Du fjernede en generator!"
  remove-others-gens: "&c✘ Du kan ikke fjerne andres generators!"
  remove-gen-block: "&c✘ Du kan ikke smadre generators!"
  max-upgrade: "&c✘ Du har opgraderet dine gens til max niveau!"
  max-gens: "&c✘ Du har ikke plads til flere generators!"
  no-money: "&c✘ Du mangler $%money% før du kan opgradere!"
  place-sell-chest: "&a✔ Du placerede en sell-chest!"
  sell-chest-placed: "&c✘ Du har allerede en sell-chest placeret!"
  sell-gui-pr-item: "&a[!] &fDu solgte &a%amount% &fitems for &a$&f%money%"
  sell-stick-all-items: "&a[!] &fDu solgte &a%amount% &fitems &a$&f%money%"

numbers:
  start-gens: 20
  start-multiplier: 1
  sell-stick-multiplier: 4
  sell-stick-name: "&6&lSELL &f&lSTICK"

sell-chest:
  name: "&3&lSELL &f&lCHEST"
  item-name: "%item% &8(&a%amount%&8)"
  lore:
    - "&a&l* &fTryk for at sælge"


